version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - "${BAZARR_PORT}:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BAZARR_CONFIG}:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
