version: "3.8"

services:
  overseerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: overseerr_stack

    labels:
      - com.centurylinklabs.watchtower.enable=true

    environment:
      - TZ=America/Phoenix

    volumes:
      - /srv/docker/seerr/config:/app/config
      - /srv/docker/seerr/assets/batman.svg:/app/public/logo_stacked.svg:ro
      - /srv/docker/seerr/assets/batman.svg:/app/public/logo_full.svg:ro

    ports:
      - "5055:5055"

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    restart: unless-stopped
