version: "3.8"

services:
  overseerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: overseerr_stack

    labels:
      - com.centurylinklabs.watchtower.enable=true

    environment:
      - TZ=America/Phoenix

    volumes:
      - /srv/docker/seerr/config:/app/config

    ports:
      - "5055:5055"

    restart: unless-stopped
