version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
    volumes:
      - /srv/docker/radarr/config:/config
      - /mnt/plex:/downloads             # MUST match SAB's /downloads
      - /mnt/plex/Movies:/Movies         # Movies library
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true