version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "${RADARR_PORT}:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${DOWNLOADS}:/downloads      # MUST match SAB's /downloads
      - ${MOVIES}:/movies
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
