version: "3.8"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8888:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /srv/local/sab/incomplete:/incomplete
      - /mnt/plex:/downloads
      - /srv/local/sab/incomplete:/incomplete-downloads
      - /srv/local/sab/complete:/downloads-local
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
