version: "3.8"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8888:8080"                 # host:container
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
      # - DOCKER_MODS=linuxserver/mods:universal-search   # optional
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /mnt/plex/Downloading:/incomplete    # temp
      - /mnt/plex:/downloads                 # finished
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
