version: "3.8"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: host                 # ← no docker0/veth; binds to host :8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /srv/local/sab/incomplete:/incomplete-downloads   # fast local temp
      - /srv/local/sab/complete:/downloads                # finished (local)
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
