version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "${SONARR_PORT}:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - SONARR__BINDADDRESS=*
      - SONARR__PORT=${SONARR_PORT}
      - SONARR__URLBASE=
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${DOWNLOADS}:/downloads      # MUST match SAB's /downloads
      - ${TV}:/tv
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
