version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
      # helpful overrides if the old DB had custom binds/urlbase
      - SONARR__BINDADDRESS=*
      - SONARR__PORT=8989
      - SONARR__URLBASE=
    volumes:
      - /srv/docker/sonarr/config:/config
      - /mnt/plex:/downloads             # MUST match SAB's /downloads
      - /mnt/plex/TV:/tv                 # TV library
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
